#!/bin/sh
#TODO: This looks up the directory where this script is located.  Can this be done simpler? --MK
DIRECTORY_OF_THIS_SCRIPT=`dirname "\`type $0\`"`
JAVA_HOME_DIR=/opt/java
JAVA_STD_CLASSES=$JAVA_HOME_DIR/lib/classes.zip
$JAVA_HOME_DIR/bin/java -asyncgc -mx100M -classpath $DIRECTORY_OF_THIS_SCRIPT/same-classes.zip:$JAVA_STD_CLASSES same.textui.SameCLI $*
